<?php

namespace Database\Seeders;

use App\Models\Diocese;
use Illuminate\Database\Seeder;

class DioceseSeeder extends Seeder
{
    public function run()
    {
        $dioceses = [
            ['name' => 'Agrigento', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Alessandria', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Ancona-Osimo', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Aosta', 'region' => 'Valle d\'Aosta', 'country' => 'Italia'],
            ['name' => 'Arezzo-Cortona-Sansepolcro', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Ascoli Piceno', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Assisi-Nocera Umbra-Gualdo Tadino', 'region' => 'Umbria', 'country' => 'Italia'],
            ['name' => 'Avellino', 'region' => 'Campania', 'country' => 'Italia'],
            ['name' => 'Bari-Bitonto', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Bologna', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Bolzano-Bressanone', 'region' => 'Trentino-Alto Adige', 'country' => 'Italia'],
            ['name' => 'Brescia', 'region' => 'Lombardia', 'country' => 'Italia'],
            ['name' => 'Caltanissetta', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Campobasso-Boiano', 'region' => 'Molise', 'country' => 'Italia'],
            ['name' => 'Casale Monferrato', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Caserta', 'region' => 'Campania', 'country' => 'Italia'],
            ['name' => 'Castellaneta', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Catania', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Catanzaro-Squillace', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Cefalù', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Cerro al Volturno', 'region' => 'Molise', 'country' => 'Italia'],
            ['name' => 'Chieti-Vasto', 'region' => 'Abruzzo', 'country' => 'Italia'],
            ['name' => 'Cividale del Friuli', 'region' => 'Friuli-Venezia Giulia', 'country' => 'Italia'],
            ['name' => 'Cosenza-Bisignano', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Cremona', 'region' => 'Lombardia', 'country' => 'Italia'],
            ['name' => 'Cuneo', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Enna', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Fabriano-Matelica', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Fermo', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Ferrara', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Firenze', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Foggia-Bovino', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Foligno', 'region' => 'Umbria', 'country' => 'Italia'],
            ['name' => 'Forlì', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Frosinone', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Genova', 'region' => 'Liguria', 'country' => 'Italia'],
            ['name' => 'Goroka', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Grosseto', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Guadaloupe', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Imola', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Isernia-Venafro', 'region' => 'Molise', 'country' => 'Italia'],
            ['name' => 'Jesi', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'L\'Aquila', 'region' => 'Abruzzo', 'country' => 'Italia'],
            ['name' => 'La Spezia', 'region' => 'Liguria', 'country' => 'Italia'],
            ['name' => 'Lamezia Terme', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Latiano', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Lecce', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Livorno', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Locri-Gerace', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Lucca', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Lucera-Troia', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Macerata-Tolentino', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Mantova', 'region' => 'Lombardia', 'country' => 'Italia'],
            ['name' => 'Massa Marittima', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Messina', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Milano', 'region' => 'Lombardia', 'country' => 'Italia'],
            ['name' => 'Modena-Nonantola', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Molfetta-Ruvo-Giovinazzo-Terlizzi', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Monreale', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Montecasario', 'region' => 'Campania', 'country' => 'Italia'],
            ['name' => 'Nardò-Gallipoli', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Nicandria', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Nicastro', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Nicosia', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Noto', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Novara', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Olbia', 'region' => 'Sardegna', 'country' => 'Italia'],
            ['name' => 'Oppido Mamertina-Palmi', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Orvieto-Todi', 'region' => 'Umbria', 'country' => 'Italia'],
            ['name' => 'Ostuni', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Padova', 'region' => 'Veneto', 'country' => 'Italia'],
            ['name' => 'Palermo', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Parma', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Pavia', 'region' => 'Lombardia', 'country' => 'Italia'],
            ['name' => 'Perugia', 'region' => 'Umbria', 'country' => 'Italia'],
            ['name' => 'Pesaro', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Pescara-Penne', 'region' => 'Abruzzo', 'country' => 'Italia'],
            ['name' => 'Piacenza-Bobbio', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Pisa', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Pistoia', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'PNicandria', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Pozzuoli', 'region' => 'Campania', 'country' => 'Italia'],
            ['name' => 'Ragusa', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Ravenna-Cervia', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Recanati', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Reggio Calabria', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Rieti', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Rimini', 'region' => 'Emilia-Romagna', 'country' => 'Italia'],
            ['name' => 'Roma', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Rossano-Cosenza', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'S. Angel in Vado', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'S. Severina', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Salerno-Campagna-Acerno', 'region' => 'Campania', 'country' => 'Italia'],
            ['name' => 'Sassari', 'region' => 'Sardegna', 'country' => 'Italia'],
            ['name' => 'Siena-Colle di Val d\'Elsa-Montalcino', 'region' => 'Toscana', 'country' => 'Italia'],
            ['name' => 'Siracusa', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Sora-Cassino-Aquino-Pontecorvo', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Sorianello', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Sicilia', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Suburbicaria di Albano', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Suburbicaria di Frascati', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Suburbicaria di Palestrina', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Suburbicaria di Porto-Santa Rufina', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Taranto', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Teano-Calvi', 'region' => 'Campania', 'country' => 'Italia'],
            ['name' => 'Temporini', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'TERAMO-Atri', 'region' => 'Abruzzo', 'country' => 'Italia'],
            ['name' => 'Terni-Narni-Amelia', 'region' => 'Umbria', 'country' => 'Italia'],
            ['name' => 'Tortona', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Trani-Barletta-Andria-Bisceglie', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Trapani', 'region' => 'Sicilia', 'country' => 'Italia'],
            ['name' => 'Trento', 'region' => 'Trentino-Alto Adige', 'country' => 'Italia'],
            ['name' => 'Tricase', 'region' => 'Puglia', 'country' => 'Italia'],
            ['name' => 'Trieste', 'region' => 'Friuli-Venezia Giulia', 'country' => 'Italia'],
            ['name' => 'Turin', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Urbino-Urbania-Sant\'Angelo in Vado', 'region' => 'Marche', 'country' => 'Italia'],
            ['name' => 'Valencia', 'region' => 'Piemonte', 'country' => 'Italia'],
            ['name' => 'Velletri-Segni', 'region' => 'Lazio', 'country' => 'Italia'],
            ['name' => 'Venezia', 'region' => 'Veneto', 'country' => 'Italia'],
            ['name' => 'Ventimiglia-San Remo', 'region' => 'Liguria', 'country' => 'Italia'],
            ['name' => 'Verona', 'region' => 'Veneto', 'country' => 'Italia'],
            ['name' => 'Vibo Valentia', 'region' => 'Calabria', 'country' => 'Italia'],
            ['name' => 'Vicenza', 'region' => 'Veneto', 'country' => 'Italia'],
            ['name' => 'Viterbo', 'region' => 'Lazio', 'country' => 'Italia'],
        ];

        foreach ($dioceses as $diocese) {
            Diocese::updateOrCreate(
                ['name' => $diocese['name']],
                $diocese
            );
        }
    }
}